### ISSUE TITLE
Transient not so transient

### ISSUE THREAD

**Issue by Ponant** [jamesmontemagno/VS2019-FirstXamarinApp#1]
Hi James,
Sorry to bother on that but I watched your video on youtube with @glennc and setting up the ItemViewModel as transient does not make it behave as transient.

For instance, the following 
`public class MyViewModel
    {
        public string DoIt { get; set; } = Guid.NewGuid().ToString();
    }`
will generate the same Guid in UWP (with a click button to invoke the service and display it on a `TextBlock`) if you set `services.AddTransient<MyViewModel>();
` or `services.AddSingleton<MyViewModel>();`, but the transient/singleton nature will behave as expected in a Asp.Net Core web app (i.e. a new guid is generated if transient lifetime is chosen upon each browser refresh).
I did not try navigation to a different page, though.

I would appreciate if you could provide an opinion on that. Thanks

**Comment by Ponant** [comment]
I actually just tried navigating to another page and come back. Here is the scenario
Page 1
-Textblock
-Click button to display Guid in the textblock by using the injected service above
-Hyperlink to go to page 2
Page 2
-Hyperlink to go to page 1

The action is then:
-go to page 1, click on button to display guid, goto page 2 and go back to page 1 and click again the button to display a guid

Results of such a navigation + click:
-Transient: A new Guid is generated
-Scoped : Same Guid reappears
-Singleton: Same as scoped

So I still don't see how to distinguish between scoped and singleton, but that is already interesting to note.

**Comment by jamesmontemagno** [comment]
Transient means a new instance of it will be created each time you try to get it. A Singleton or scoped would return the same each time. Does that makes sense?

**Comment by haideralicspak** [comment]
hey @jamesmontemagno this may sound stupid to ask here but your video have a animation on click of the entry where placeholder floats above on entry. I have seen the code but couldnt found how that works please can you explain how is it animating from placeholder to title? Thanks

**Comment by jamesmontemagno** [comment]
@haideralicspak  look at: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual
